-- SELECT 
--   employees.first_name AS first, employees.last_name AS last, 
--   departments.department_name AS department_name, roles.title AS role_name
-- FROM employees
-- JOIN departments ON employees.department_id = departments.id
-- JOIN roles ON employees.role_id = roles.id
